language: node_js
node_js:
  - 13

env:
  - APPLICATION_FOLDER=udagram-frontend DOCKER_NAME=udagram-frontend
  - APPLICATION_FOLDER=udagram-feed-api DOCKER_NAME=udagram-feed-api
  - APPLICATION_FOLDER=udagram-user-api DOCKER_NAME=udagram-user-api
  - APPLICATION_FOLDER=udagram-reverse-proxy DOCKER_NAME=udagram-reverse-proxy

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t "$DOCKER_NAME" ./"$APPLICATION_FOLDER"
  - docker tag "$DOCKER_NAME" robertem/"$DOCKER_NAME":latest

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push robertem/$DOCKER_NAME