apiVersion: v1
kind: ConfigMap
metadata:
  name: udagram-config
data:
  POSTGRES_USERNAME: 
  POSTGRES_PASSWORD: 
  POSTGRES_HOST: 
  POSTGRES_DB: 
  AWS_BUCKET: 
  AWS_REGION: 
  AWS_PROFILE: 
  JWT_SECRET: 
  URL: 