apiVersion: v1
kind: Service
metadata:
  name: udagram-svc
  labels:
    app: udagram-reverse-proxy
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: udagram-reverse-proxy
  type: LoadBalancer