apiVersion: v1
kind: Service
metadata:
  name: udagram-web
  labels:
    run: udagram-frontend
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: udagram-frontend
---
apiVersion: v1
kind: Service
metadata:
  name: udagram-svc
  labels:
    run: udagram-reverse-proxy
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: udagram-reverse-proxy
---
apiVersion: v1
kind: Service
metadata:
  name: user-svc
  labels:
    run: udagram-user-api
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: udagram-user-api
---
apiVersion: v1
kind: Service
metadata:
  name: feed-svc
  labels:
    run: udagram-feed-api
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: udagram-feed-api